### PR TITLE
Add arm64 support to the container

### PR DESCRIPTION
**Pull request by lhw**
I spent some time trying to get arm64 to work and I somehow managed by referencing the excellent palworld server by [thijsvanloef](https://github.com/thijsvanloef/palworld-server-docker).

There is quite a bit of debug logging going on so I am keeping this as draft to check if there are any issues that stem from that.

Caveats so far:
- Without running steamcmd.sh with qemu-i386-static it will show progress downloading but sometimes just stops without any error codes.
- The startup takes quite a while on the oracle cloud free tier 4c/24gb but it seems to run fine afterwards.
- Right now the container runs as user steam without changeable UID/GID, but that was only to avoid issues due to permissions while debugging.

Oh and I changed the exec flags on all the files that are not being executed.

### CODE REVIEW

**Comment by TrueOsiris** [comment]
In the meantime (just before u created the merge request), I've merged with the fork from Diyagi, who mainly added startup/shutdown functionality to start.sh and better log management. Please try to catch up to the latest version.

I read that your fork is still a WiP. Please create a new merge request when you finished, or let me know when it's done.
I'm certainly willing to add an :arm64 tag to this image for an arm version.

**Comment by lhw** [comment]
Fixes:
1. This seems to work much better now even without compatibility mode. But i'll leave it in
2. It feels like the ampere cores, even with their 3.0GHz are exceptionally slow. Or the ARM + windows emulation takes a heavy toll. I don't think I can run the v-rising on oracle cloud
3. Added this back in

Bugs:
1. Even with the attempted fix in (https://github.com/TrueOsiris/docker-vrising/pull/54/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R20) sometimes it doesn't seem to correctly install the wineprefix causing lots of certificate/crypto errors. I have not found a good solution as of yet.

**Comment by lhw** [comment]
> In the meantime (just before u created the merge request), I've merged with the fork from Diyagi, who mainly added startup/shutdown functionality to start.sh and better log management. Please try to catch up to the latest version.

I saw. I had most changes already inluded anyhow. The conflict with the start.sh is unavoidable right now. The only thing I could do is rebase, but given that there are still some issues I dont think its worth the time.

> I read that your fork is still a WiP. Please create a new merge request when you finished, or let me know when it's done. I'm certainly willing to add an :arm64 tag to this image for an arm version.

Yea I might do that. This seems to become its own thing given the scope of changes.

**Comment by lhw** [comment]
The latest version in my branch does start the server. But there are definitely some issues in regards to actually running the server, as in architecture related issues. Sometimes your character just gets teleported straight out of the map, lots of server crashes.

I think for now arm64 is not an option with wine emulation. It might be doable when they finally release a linux build of the server.

**Pull request closed without merging**
