### PR TITLE
Readme cleanup + logos

### PR DESCRIPTION
**Pull request by mattiasghodsian**
I have cleanup and "Beautified " the readme file and also created logos for this repo

### CODE REVIEW

**Comment by TrueOsiris** [comment]
I like the logo and changes, but before I merge, I want to see one thing changed:
The ports. That line on the 27K ports isn't entirely correct, I believe.

If the two ports in the ServerHostSettings.json and thus the internal docker ports match the exposed ports, the server will be visible in the public serverlist. So, the server will be seen in the public list only if the following 3 settings are true:

1.
- /server/VRisingServer_Data/StreamingAssets/Settings/ServerHostSettings.json contains both
```
  "Port": 9995,
  "QueryPort": 9996,
```
and 
```  
"ListOnMasterServer": true,
```
2. the exposed container ports are 9995/udp and 9996/udp.

3. In your firewall settings, these 2 ports (udp) are forwarded from wan to these 2 udp ports on your dockerhost ip .

**Comment by TrueOsiris** [comment]
And though I like the logo, I'm not sure I'm allowed to use my name mixed with their game. I'm not going to risk getting that angry mail, to be honest. Can you just do the V with trueosiris ? :-D

**Comment by mattiasghodsian** [comment]
> And though I like the logo, I'm not sure I'm allowed to use my name mixed with their 'full' gamename. I'm not going to risk getting that angry mail, to be honest. Could you just do the V with trueosiris ?

Done

**Comment by mattiasghodsian** [comment]
I don't think they will care about that, I removed you'r name and just have the repo name there !?

**Pull request merged**
